#!/bin/bash

set -eu

if [ ! -e .env ]; then
    cp .env-template .env
    echo "Created a new .env file.  Edit to suit your needs and re-run _build_env."
    exit 1
fi

source .env

${PYTHON_BIN} -m venv .venv --prompt=${APP_NAME}
source .venv/bin/activate
pip install -q -U pip setuptools wheel

PYTHON=${PYTHON_BIN} VIRTUAL_ENV=${VIRTUAL_ENV} bash _build_s2

export LDFLAGS="-L${VIRTUAL_ENV}/lib -Wl,-rpath=${VIRTUAL_ENV}/lib"
export CXXFLAGS="-I${VIRTUAL_ENV}/include"

pip install -r requirements.local.txt

echo -e "\n\nVirtual environment is ready.  'source _activate' to use it.\n\n"
