#!/bin/bash -eu

if [ ! -e .env ]; then
    cp .env-template .env
    echo "Created a new .env file.  Edit to suit your needs and re-run _build_env."
    exit 1
fi

source .env

$PYTHON_3_9_OR_HIGHER -m venv .venv --prompt=$APP_NAME
source .venv/bin/activate
pip install -q -U pip setuptools wheel

# set S2PREFIX for _install_s2 and complier flags for sbsearch
export S2PREFIX=$VIRTUAL_ENV
export LDFLAGS="-L$S2PREFIX/lib -Wl,-rpath=$S2PREFIX/lib"
export CXXFLAGS="-I$S2PREFIX/include"

./_install_s2

pip install -r requirements.dev.txt

echo -e "\n\nVirtual environment is ready.  'source _activate' to use it.\n\n"
