#! /bin/bash

clear

echo """
==============================================
    Running flask API in development mode.

    API will be refreshed on code changes.

    Logging is to console.
==============================================
"""

sleep 2

nodemon -w 'src/catch_apis/**' -e py,yaml --exec python3 -m catch_apis.api.app
