#! /bin/bash

clear

echo """
==================================================

    Running single worker in development mode.
    Worker will be refreshed on code changes.

    An active redis server is required;
    use _redis_manager to set one up.

    Logging is to console.

==================================================
"""

sleep 2

echo $PYTHONPATH
nodemon -w 'src/**' -e py,yaml --exec python3 src/scripts/worker.py
