#! /bin/bash

clear

echo """
==============================================
    Running flask API in development mode.

    API will be refreshed on code changes.

    Logging is to console.
==============================================
"""

sleep 2

nodemon -w 'src/**' -w '.venv/lib/python3.8/site-packages/flask_restplus/templates/swagger-ui.html' -e py,html --exec python src/app_entry.py
