#!/bin/sh

WORKERS=`test $GUNICORN_FLASK_INSTANCES -lt 0 && nproc || echo $GUNICORN_FLASK_INSTANCES`

gunicorn catch_apis.app \
  --name $GUNICORN_APP_NAME \
  --workers $WORKERS \
  --timeout 600 \
  --bind '0.0.0.0:'$API_PORT
