#! /bin/bash

clear

source .env

echo """
===============================================================

    RUNNING PIPELINE TO ADD NAME-SEARCH FUNCTIONALITY TO DB

(Hint: add 1-3 numbered args to run subsections of the pipeline)

===============================================================
"""

sleep 2

# If args aren't provided, assign default values to choice_* vars
# Note syntax: FOO=${VARIABLE:-default}  # If variable not set or null, use default.
choice_lower=${1:-0}
choice_upper=${3:-3}

echo "Running stages "$choice_lower" to "$choice_upper

sleep 2

# function to decide whether or not stage is to be executed
runStage() {
  stage=$1
  if [[ -z $1 ]]; then
    echo "runStage must receive an argument"
    exit 1
  fi
  if [[ $stage -ge $choice_lower && $stage -le $choice_upper ]]; then
    echo true
  else
    echo false
  fi
}

if $(runStage 0); then
  echo "<<<RUNNING STAGE 0>>>"
  python name-search/stage0.py
fi

if $(runStage 1); then
  echo "<<<RUNNING STAGE 1>>>"
  python name-search/stage1.py
fi

if $(runStage 2); then
  echo "<<<RUNNING STAGE 2>>>"
  python name-search/stage2.py
fi

if $(runStage 3); then
  echo "<<<RUNNING STAGE 2>>>"
  python name-search/stage3.py
fi
