#! /bin/bash

# Run this script in separate window to enable access to
# remote file system while working on local development

# Load vars defined in .env
source .env

# Run sshfs as a simple foreground process
cmd="sshfs -f $CATCH_REMOTE_LINUX_USER@$CATCH_REMOTE_LINUX_HOST:/ $CATCH_LOCAL_ROOT_PATH"
eval $cmd
