#!/bin/sh

# -------------------------------------------------------------
# Wrapper around our manager scripts to give an overview of the
# status of the app's production tools
# -------------------------------------------------------------

clear

echo """
------------------------------
"""

./_gunicorn_manager status

echo """
------------------------------
"""

./_redis_manager status

echo """
------------------------------
"""

./_worker_manager status

echo """
------------------------------
"""
