version: "3.8"

services:
  apis:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: catch-prod
    container_name: catch-apis-prod-${DEPLOYMENT_TIER}
    command: ./_entrypoint_webapp_prod
    tty: true
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    depends_on:
      - redis-server
    restart: always
  worqer-prod:
    image: catch-prod
    deploy:
      replicas: ${CATCH_QUEUE_WORKER_INSTANCES}
    labels:
      deployment_tier: ${DEPLOYMENT_TIER}
    command: ./_entrypoint_woRQer_prod
    depends_on:
      - redis-server
      - apis
    restart: always
    env_file:
      - ./.env
  redis-server:
    image: redis:5
    restart: always
    container_name: catch-redis-prod-${DEPLOYMENT_TIER}
