version: "3.8"

services:
  apis:
    build:
      context: ./services/apis
      dockerfile: Dockerfile.prod
    image: catch-prod
    container_name: apis-prod
    command: ./_entrypoint_flask_prod
    tty: true
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./.env
    depends_on:
      - redis-server
  woRQer:
    build:
      context: ./services/apis
      dockerfile: Dockerfile.prod
    image: catch-prod
    container_name: worqer-prod
    command: ./_entrypoint_woRQer_prod
    depends_on:
      - redis-server
    env_file:
      - ./.env
  redis-server:
    image: redis:5
