### Pull official base image with Debian OS
FROM python:3.11.8-slim-bookworm

### Set work directory
WORKDIR /app

### Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LDFLAGS "-L/usr/local/lib -Wl,-rpath=/usr/local/lib"
ENV CXXFLAGS="-I/usr/local/include"

### Install system dependencies
RUN apt-get update && apt-get install -y \
  # Stuff for our flask app
  netcat-openbsd \
  nodejs \
  npm \
  # Useful stuff
  vim \
  # Stuff for S2 Geometry: https://s2geometry.io/about/platforms
  git \
  wget \
  libgflags-dev \
  libgoogle-glog-dev \
  libgtest-dev \
  libssl-dev \
  swig \
  cmake

### Add some tools to make trouble-shooting in container easier
SHELL ["/bin/bash", "-c"]
RUN source <(wget -qO- https://raw.githubusercontent.com/d-w-d/myconfig/master/quickstart.sh)  \
  && myconfig install -y self

### Install nodemon
RUN npm i -g nodemon

### Install S2; see: https://s2geometry.io/about/platforms
COPY ./_install_s2 .
RUN ./_install_s2

### Install python dependencies
RUN pip install --upgrade pip
RUN pip install --upgrade -q -q -q setuptools wheel cython
COPY ./requirements.txt .
RUN mkdir /catchlibs
RUN pip install --src /catchlibs -r requirements.txt

# Start up command issued in docker-compose files