version: "3.8"

services:
  apis:
    build: ./services/apis
    image: catch-apis-dev
    container_name: catch-apis-dev
    command: ./_entrypoint_flask
    volumes:
      - ./services/apis/:/app/
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis-server
    env_file:
      - ./.env
  woRQer:
    build: ./services/apis
    image: catch-apis-dev
    container_name: woRQer-dev
    command: ./_entrypoint_woRQer
    volumes:
      - ./services/apis/:/app/
    depends_on:
      - db
      - redis-server
    env_file:
      - ./.env
  db:
    image: postgres:13-alpine
    container_name: catch-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./.pg-init-data/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  redis-server:
    image: redis:5

volumes:
  postgres_data:
