version: "3.8"

services:
  apis:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: catch-dev
    container_name: catch-apis-dev
    command: ./_entrypoint_webapp
    volumes:
      - app:/app
      - .:/app/src
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    depends_on:
      - redis-server
    env_file:
      - ./.env
  woRQer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: catch-dev
    container_name: catch-woRQer-dev
    command: ./_entrypoint_woRQer
    volumes:
      - app:/app
      - .:/app/src
    depends_on:
      - redis-server
    env_file:
      - ./.env
  redis-server:
    image: redis:5
volumes:
  app:
