#!/bin/sh

if [ "$DATABASE" = "postgres" ]; then
  echo "Waiting for postgres..."

  while ! nc -z $SQL_HOST $SQL_PORT; do
    sleep 0.1
  done

  echo "PostgreSQL started"
fi

# for i in {1..5}; do
#   # rq worker
#   python -m src.woRQers.woRQer &
# done

python -m src.woRQers.woRQer
