#!/bin/sh

if [ "$DATABASE" = "postgres" ]; then
  echo "Waiting for postgres..."

  while ! nc -z $SQL_HOST $SQL_PORT; do
    sleep 0.1
  done

  echo "PostgreSQL started"
fi

gunicorn src.api.app \
  --config src/config/gunicorn-flask.py \
  --name $GUNICORN_APP_NAME \
  --timeout 600 \
  --bind '0.0.0.0:'$API_PORT
